version: 2.1

orbs:
  yarn: artsy/yarn@6.0.0
  auto: artsy/auto@1.4.0

workflows:
  build_and_verify:
    jobs:
      - yarn/update-cache
      - yarn/test
      - auto/publish-canary:
          context: npm-deploy
          filters:
            branches:
              ignore: main
          requires:
            - yarn/test
            - yarn/update-cache
      - auto/publish:
          context: npm-deploy
          filters:
            branches:
              only: main
          requires:
            - yarn/test
            - yarn/update-cache
